In [1]:
import pandas as pd
import numpy as np

In [69]:
data =  pd.read_csv('src/assets/cluster2frame.csv')
ct = pd.crosstab(index = data.Source, columns = data.Target)

In [70]:
data

Source           Target
0                psg         neymarjr
1                psg        danialves
2                psg      davidluiz_4
3                psg      lucasmoura7
4                psg   thiagosilva_33
5        negodoborel             kaka
6        negodoborel              psg
7        negodoborel  alexandrepires_
8        negodoborel      galvaobueno
9        negodoborel        bruninho1
10       negodoborel             pato
11       negodoborel          ronaldo
12       negodoborel     davidbeckham
13       negodoborel     justinbieber
14       negodoborel   euandremarques
15       negodoborel       caiocastro
16       negodoborel         seujorge
17       negodoborel      10emerson10
18       negodoborel        ticoelias
19       negodoborel        hugogloss
20       negodoborel    gabrielmedina
21       negodoborel       neymarpai_
22       negodoborel        tgmartins
23       negodoborel      hulkparaiba
24       negodoborel   andre_santos27
25       negodoborel   thiagosilva_33
26       negodoborel      fredguedes9
27       negodoborel       paulinhop8
28       negodoborel      davidluiz_4
29       negodoborel    oscar_emboaba
...              ...              ...
1054    tiagoleifert   andreolifelipe
1055    tiagoleifert   euandremarques
1056    tiagoleifert      galvaobueno
1057    tiagoleifert        thbarbosa
1058    tiagoleifert          ronaldo
1059    tiagoleifert             kaka
1060    tiagoleifert         neymarjr
1061     kellyslater     filipetoledo
1062     kellyslater       m_phelps00
1063     kellyslater     danbilzerian
1064       hugogloss       neymarpai_
1065       hugogloss              psg
1066       hugogloss         tombrady
1067  rodrigobocardi   andreolifelipe
1068  rodrigobocardi   gentilfernanda
1069  rodrigobocardi     tiagoleifert
1070  rodrigobocardi      pedroscooby
1071  rodrigobocardi         leomessi
1072  rodrigobocardi         neymarjr
1073  rodrigobocardi      galvaobueno
1074  rodrigobocardi        hugogloss
1075      caiocastro     davidbeckham
1076      caiocastro    rubarrichello
1077      caiocastro     danbilzerian
1078      caiocastro     justinbieber
1079      caiocastro         neymarjr
1080      caiocastro     bobburnquist
1081      caiocastro      pedroscooby
1082      caiocastro      kellyslater
1083      caiocastro    gabrielmedina

[1084 rows x 2 columns]

In [71]:
sset = set(np.unique(data.Source))
len(sset)

68

In [72]:
tset = set(np.unique(data.Target)) 
len(tset)

72

In [78]:
diff = tset.difference(sset)

In [81]:
ct_out = ct

In [82]:
ct_out = ct_out.drop(diff, axis=1)
ct_out

Target                   10emerson10  16lucassilva  acelerados  \
Source                                                           
10emerson10                        0             0           0   
16lucassilva                       0             0           0   
acelerados                         0             0           0   
alexandrepires_                    1             0           0   
andersonvarejao18                  0             0           0   
andre_santos27                     1             0           0   
andreolifelipe                     1             0           0   
bobburnquist                       0             0           0   
bruninho1                          1             0           0   
cacabuenoracing                    0             0           0   
caiocastro                         0             0           0   
carlosburle                        0             0           0   
danbilzerian                       0             0           0   
danialves                          0             0           0   
dantebahia                         0             0           0   
davidbeckham                       0             0           0   
davidluiz_4                        0             0           0   
edmundosouza10                     0             0           0   
euandremarques                     0             0           0   
filipetoledo                       0             0           0   
flaviocanto                        0             0           0   
fredguedes9                        0             1           0   
gabrielmedina                      0             0           0   
gabrielopensadoroficial            0             0           0   
galvaobueno                        0             0           0   
gentilfernanda                     0             0           0   
guimemc                            0             0           0   
hugogloss                          0             0           0   
hulkparaiba                        1             0           0   
john_john_florence                 0             0           0   
...                              ...           ...         ...   
m_phelps00                         0             0           0   
marcelotwelve                      1             1           0   
marcusbuaiz                        0             0           0   
massafelipe19                      0             0           1   
maya                               0             0           0   
negodoborel                        1             0           0   
neymarjr                           0             0           0   
neymarpai_                         0             0           0   
oficialthiagopereira               1             0           0   
olympics                           0             0           0   
oscar_emboaba                      0             0           0   
papatinho                          0             0           0   
pato                               0             0           0   
paulinhop8                         1             0           0   
pedroscooby                        1             0           0   
psg                                0             0           0   
rami7oficial                       0             0           0   
rodrigobocardi                     0             0           0   
ronaldo                            1             0           0   
rubarrichello                      0             0           1   
tarsomarquesoficial                0             0           0   
tgmartins                          1             0           0   
thbarbosa                          1             0           0   
thiagosilva_33                     1             0           0   
tiagoleifert                       0             0           0   
ticoelias                          0             0           0   
timebrasil                         0             0           0   
tkanaan                            0    

In [170]:
def pagerank(matrix, gamma, n_iter=None):
    print(matrix.shape)
    tele = np.ones((np.alen(matrix), np.alen(matrix[0])))
    tele = np.matrix([t/sum(t) for t in tele])
    rw = []
    for row in matrix:
        if(all(row == 0)):
            rw.append(row)
        else:
            rw.append(row/sum(row))
    rw = np.matrix(rw)
    P = (rw*gamma) + ((1-gamma)*tele)
    if n_iter is not None:
        for i in range(0, n_iter):
            P = P*P
            print(P)
    else:
        P_before = np.zeros(P.shape)
        while not all((P_before-P) == 0):
            P_before = P
            P = P*P
            print(P)
    return P

In [171]:
m = np.array([[1, 0, 1], [0, 0, 1], [0,1,0]])
pagerank(m, 0.5, 5)

(3, 3)
[[0.27083333 0.375      0.35416667]
 [0.20833333 0.5        0.29166667]
 [0.20833333 0.25       0.54166667]]
[[0.22526042 0.37760417 0.39713542]
 [0.22135417 0.40104167 0.37760417]
 [0.22135417 0.33854167 0.44010417]]
[[0.22223409 0.37094116 0.40682475]
 [0.22221883 0.37225342 0.40552775]
 [0.22221883 0.36834717 0.409434  ]]
[[0.22222222 0.37037263 0.40740515]
 [0.22222222 0.37037772 0.40740006]
 [0.22222222 0.37036246 0.40741532]]
[[0.22222222 0.37037037 0.40740741]
 [0.22222222 0.37037037 0.40740741]
 [0.22222222 0.37037037 0.40740741]]


matrix([[0.22222222, 0.37037037, 0.40740741],
        [0.22222222, 0.37037037, 0.40740741],
        [0.22222222, 0.37037037, 0.40740741]])

In [172]:
rank = pagerank(ct_out.as_matrix(), 0.85,5)
rank

(68, 68)
[[0.02484439 0.00246317 0.00259576 ... 0.00524856 0.01595705 0.0047166 ]
 [0.01537546 0.0122972  0.00259576 ... 0.0114819  0.02316897 0.01258121]
 [0.00731728 0.00246317 0.01928829 ... 0.01263956 0.01156939 0.0029544 ]
 ...
 [0.0077734  0.00607567 0.01008579 ... 0.03442339 0.01933979 0.0029544 ]
 [0.01537546 0.00748054 0.00259576 ... 0.00666523 0.0365486  0.01258121]
 [0.00366829 0.00246317 0.00259576 ... 0.00312356 0.00498313 0.0029544 ]]
[[0.01418705 0.00395798 0.0035046  ... 0.00568069 0.02357636 0.00875723]
 [0.0139105  0.00414749 0.0036527  ... 0.00602183 0.02306966 0.00854766]
 [0.01217147 0.00379033 0.0045415  ... 0.0066515  0.02247271 0.00858609]
 ...
 [0.01295709 0.00398924 0.0047365  ... 0.00747178 0.02275156 0.00885416]
 [0.01380473 0.00417686 0.00361389 ... 0.00584682 0.02465476 0.00832028]
 [0.01102485 0.00326191 0.00329894 ... 0.00582827 0.0250612  0.00885393]]
[[0.01341462 0.00394539 0.00365128 ... 0.00573379 0.02329842 0.00897951]
 [0.01338864 0.00394119 0.0036

matrix([[0.01336589, 0.00393779, 0.00364784, ..., 0.00573034, 0.02326842,
         0.00900702],
        [0.01336589, 0.00393779, 0.00364784, ..., 0.00573034, 0.02326842,
         0.00900702],
        [0.01336589, 0.00393779, 0.00364784, ..., 0.00573034, 0.02326842,
         0.00900702],
        ...,
        [0.01336589, 0.00393779, 0.00364784, ..., 0.00573034, 0.02326842,
         0.00900702],
        [0.01336589, 0.00393779, 0.00364784, ..., 0.00573034, 0.02326842,
         0.00900702],
        [0.01336589, 0.00393779, 0.00364784, ..., 0.00573034, 0.02326842,
         0.00900702]])

In [183]:
data_out = pd.DataFrame(data=np.squeeze(np.asarray(rank[0])), index=ct_out.columns)

In [184]:
data_out.to_csv('src/assets/pagerank68')

In [185]:
ct_in = ct

In [186]:
missing_data = pd.DataFrame(index=diff,data=np.zeros((4,72)), columns = ct.columns)
missing_data

Target             10emerson10  16lucassilva  acelerados  aecionevesoficial  \
snoopdogg                  0.0           0.0         0.0                0.0   
seujorge                   0.0           0.0         0.0                0.0   
bobsinclar                 0.0           0.0         0.0                0.0   
aecionevesoficial          0.0           0.0         0.0                0.0   

Target             alexandrepires_  andersonvarejao18  andre_santos27  \
snoopdogg                      0.0                0.0             0.0   
seujorge                       0.0                0.0             0.0   
bobsinclar                     0.0                0.0             0.0   
aecionevesoficial              0.0                0.0             0.0   

Target             andreolifelipe  bobburnquist  bobsinclar      ...       \
snoopdogg                     0.0           0.0         0.0      ...        
seujorge                      0.0           0.0         0.0      ...        
bobsinclar                    0.0           0.0         0.0      ...        
aecionevesoficial             0.0           0.0         0.0      ...        

Target             tarsomarquesoficial  tgmartins  thbarbosa  thiagosilva_33  \
snoopdogg                          0.0        0.0        0.0             0.0   
seujorge                           0.0        0.0        0.0             0.0   
bobsinclar                         0.0        0.0        0.0             0.0   
aecionevesoficial                  0.0        0.0        0.0             0.0   

Target             tiagoleifert  ticoelias  timebrasil  tkanaan  tombrady  \
snoopdogg                   0.0        0.0         0.0      0.0       0.0   
seujorge                    0.0        0.0         0.0      0.0       0.0   
bobsinclar                  0.0        0.0         0.0      0.0       0.0   
aecionevesoficial           0.0        0.0         0.0      0.0       0.0   

Target             vitorbelfort  
snoopdogg                   0.0  
seujorge                    0.0  
bobsinclar                  0.0  
aecionevesoficial           0.0  

[4 rows x 72 columns]

In [187]:
ct_in = ct_in.append(missing_data)

In [190]:
data_in = pagerank(ct_in.as_matrix(), 0.85, 10)

(72, 72)
[[0.00716949 0.00231793 0.00242538 ... 0.00291411 0.03202819 0.00565364]
 [0.01896739 0.00231793 0.00596704 ... 0.00999744 0.00820243 0.00276364]
 [0.01033541 0.00231793 0.00242538 ... 0.01294883 0.00466077 0.00625398]
 ...
 [0.00159602 0.0005471  0.00065454 ... 0.00114327 0.00288993 0.00099281]
 [0.00159602 0.0005471  0.00065454 ... 0.00114327 0.00288993 0.00099281]
 [0.00159602 0.0005471  0.00065454 ... 0.00114327 0.00288993 0.00099281]]
[[0.01043461 0.00352229 0.00495636 ... 0.00468155 0.01752915 0.00459742]
 [0.01010924 0.00362901 0.00513803 ... 0.00432722 0.01964071 0.00491075]
 [0.01037072 0.00327393 0.004286   ... 0.00442128 0.01395932 0.00383943]
 ...
 [0.00142609 0.00050122 0.00066753 ... 0.0006745  0.0024932  0.00066254]
 [0.00142609 0.00050122 0.00066753 ... 0.0006745  0.0024932  0.00066254]
 [0.00142609 0.00050122 0.00066753 ... 0.0006745  0.0024932  0.00066254]]
[[0.0085169  0.00300222 0.00412587 ... 0.00410646 0.01535514 0.004014  ]
 [0.00867103 0.0030571  0.0042

In [192]:
fin_csv = pd.DataFrame(data=np.squeeze(np.asarray(data_in[0])), index=ct_in.columns)

In [193]:
fin_csv

0
Target                               
10emerson10              1.451131e-17
16lucassilva             5.117727e-18
acelerados               7.034900e-18
aecionevesoficial        4.400905e-18
alexandrepires_          1.586767e-17
andersonvarejao18        9.774531e-18
andre_santos27           1.138126e-17
andreolifelipe           1.996788e-17
bobburnquist             1.491840e-17
bobsinclar               3.555249e-18
bruninho1                1.939457e-17
cacabuenoracing          1.220880e-17
caiocastro               1.583309e-17
carlosburle              1.365789e-17
danbilzerian             2.316634e-17
danialves                3.351593e-17
dantebahia               9.918280e-18
davidbeckham             5.883487e-17
davidluiz_4              2.447935e-17
edmundosouza10           7.558758e-18
euandremarques           1.412795e-17
filipetoledo             2.329376e-17
flaviocanto              1.001277e-17
fredguedes9              1.464153e-17
gabrielmedina            4.290098e-17
gabrielopensadoroficial  1.182325e-17
galvaobueno              1.839859e-17
gentilfernanda           2.749925e-17
guimemc                  8.477511e-18
hugogloss                2.840026e-17
...                               ...
marcusbuaiz              8.055318e-18
massafelipe19            1.544732e-17
maya                     1.242223e-17
negodoborel              1.173362e-17
neymarjr                 7.352772e-17
neymarpai_               2.609005e-17
oficialthiagopereira     1.041822e-17
olympics                 1.244280e-17
oscar_emboaba            1.381376e-17
papatinho                5.247484e-18
pato                     1.530908e-17
paulinhop8               2.558651e-17
pedroscooby              2.257550e-17
psg                      2.556133e-17
rami7oficial             6.995018e-18
rodrigobocardi           3.302523e-18
ronaldo                  4.309777e-17
rubarrichello            3.416897e-17
seujorge                 2.560248e-17
snoopdogg                1.328697e-17
tarsomarquesoficial      6.520716e-18
tgmartins                3.951615e-17
thbarbosa                2.311317e-17
thiagosilva_33           3.305059e-17
tiagoleifert             1.641815e-17
ticoelias                1.406944e-17
timebrasil               1.314098e-17
tkanaan                  7.000520e-18
tombrady                 2.615774e-17
vitorbelfort             6.841001e-18

[72 rows x 1 columns]

In [195]:
fin_csv.to_csv('src/assets/pagerank72.csv')